name: Test CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      test: test
    name: 'Call test task'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Set up JDK'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: 'Set up Gradle'
        uses: gradle/actions/setup-gradle@v4
      - name: 'Build with Gradle'
        run: ./gradlew --stacktrace --info test
